<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ersa.Mes.FileSystem</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <Reference Include="AutoMapper">
      <HintPath>bin\Debug\net472\AutoMapper.dll</HintPath>
    </Reference>
    <Reference Include="Ersa.Mes.Common">
      <HintPath>bin\Debug\net472\Ersa.Mes.Common.dll</HintPath>
    </Reference>
    <Reference Include="Ersa.Mes.Logging">
      <HintPath>bin\Debug\net472\Ersa.Mes.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>bin\Debug\net472\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>