using System.ComponentModel;
using Ersa.Mes.Common.Description;
using Ersa.Mes.Common.Extensions;

namespace Ersa.Mes.Middleware.Definition;

public enum Enum_MesFunction
{
	[Description("</STRUCT_RezeptAuswaehlen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("ChooseRecipe_Request")]
	[DescriptionChinese("选择焊接程序_请求")]
	RezeptAuswaehlen_Anfo_EL,
	[Description("</STRUCT_RezeptAuswaehlen_Stat_EL>")]
	[Edc_MesFunctionEnglish("ChooseRecipe_Response")]
	[DescriptionChinese("选择焊接程序_反馈")]
	RezeptAuswaehlen_Stat_LE,
	[Description("</STRUCT_RezeptBestaetigen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Confirm_Recipe")]
	[DescriptionChinese("确认焊接程序_请求")]
	RezeptBestaetigen_Anfo_EL,
	[Description("</STRUCT_EinlaufFreigeben_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Release_Infeed_Request")]
	[DescriptionChinese("进板释放_请求")]
	EinlaufFreigeben_Anfo_EL,
	[Description("</STRUCT_EinlaufFreigeben_Stat_EL>")]
	[Edc_MesFunctionEnglish("Release_Infeed_Response")]
	[DescriptionChinese("进板释放_反馈")]
	EinlaufFreigeben_Stat_LE,
	[Description("</STRUCT_PcbEingelaufen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Pcb_Infeed_Request")]
	[DescriptionChinese("PCB进板_请求")]
	PcbEingelaufen_Anfo_EL,
	[Description("</STRUCT_AuslaufProtokollErstellen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Outfeed_Create_Protocol_Request")]
	[DescriptionChinese("出板创建焊接报告_请求")]
	AuslaufProtokollErstellen_Anfo_EL,
	[Description("</STRUCT_AuslaufProtokollErstellen_Stat_LE>")]
	[Edc_MesFunctionEnglish("Outfeed_Create_Protocol_Response")]
	[DescriptionChinese("出板创建焊接报告_反馈")]
	AuslaufProtokollErstellen_Stat_LE,
	[Description("</STRUCT_AuslaufFreigeben_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Release_Outfeed_Request")]
	[DescriptionChinese("出板释放_请求")]
	AuslaufFreigeben_Anfo_EL,
	[Description("</STRUCT_AuslaufFreigeben_Stat_LE>")]
	[Edc_MesFunctionEnglish("Release_Outfeed_Response")]
	[DescriptionChinese("出板释放_反馈")]
	AuslaufFreigeben_Stat_LE,
	[Description("</STRUCT_PcbAusgelaufen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Pcb_Outfeed_Request")]
	[DescriptionChinese("PCB出站_请求")]
	PcbAusgelaufen_Anfo_EL,
	[Description("</STRUCT_Maschinenzustand_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Machine_Condition_Request")]
	[DescriptionChinese("机器状态OEE_请求")]
	Maschinenzustand_Anfo_EL,
	[Description("</STRUCT_VerlustzeitenMelden_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Loss_Times_Report_Request")]
	[DescriptionChinese("报告_请求")]
	VerlustzeitenMelden_Anfo_EL,
	[Description("</STRUCT_VerlustzeitenMelden_Stat_LE>")]
	[Edc_MesFunctionEnglish("Loss_Times_Report_Response")]
	[DescriptionChinese("报告_请求")]
	VerlustzeitenMelden_Stat_LE,
	[Description("</STRUCT_TestmodusAuswaehlen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Select_Test_Mode_Request")]
	[DescriptionChinese("选择测试模式_请求")]
	TestmodusAuswaehlen_Anfo_EL,
	[Description("</STRUCT_StatusinformationAnzeigen_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Show_Status_Information_Request")]
	[DescriptionChinese("显示状态信息_请求")]
	StatusinformationAnzeigen_Anfo_LE,
	[Description("</STRUCT_PopupAnzeigen_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Ersa_PopupDialog_Request")]
	[DescriptionChinese("Ersa弹出对话框_请求")]
	PopupAnzeigen_Anfo_LE,
	[Description("</STRUCT_MeldungenUebertragen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Transfer_Messages_Request")]
	[DescriptionChinese("传递信息_请求")]
	MeldungenUebertragen_Anfo_EL,
	[Description("</STRUCT_ParameterUebertragen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Transfer_Process_Parameter_Request")]
	[DescriptionChinese("传递过程参数_请求")]
	ParameterUebertragen_Anfo_EL,
	[Description("</STRUCT_ParameterzeitspanneEmpfangen_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Receive_Period_Of_Time_Parameter_Request")]
	[DescriptionChinese("接收一段时间的参数_请求")]
	ParameterzeitspanneEmpfangen_Anfo_LE,
	[Description("</STRUCT_HeartbeatAuswerten_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Heartbeat_Evaluate_Request")]
	[DescriptionChinese("评估心跳_请求")]
	HeartbeatAuswerten_Anfo_LE,
	[Description("</STRUCT_HeartbeatAuswerten_Stat_EL>")]
	[Edc_MesFunctionEnglish("Heartbeat_Evaluate_Response")]
	[DescriptionChinese("评估心跳_反馈")]
	HeartbeatAuswerten_Stat_EL,
	[Description("</STRUCT_Initialisierung_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Initialize_Request")]
	[DescriptionChinese("初始化_请求")]
	Initialisierung_Anfo_EL,
	[Description("</STRUCT_Initialisierung_Stat_LE>")]
	[Edc_MesFunctionEnglish("Initialize_Response")]
	[DescriptionChinese("初始化_反馈")]
	Initialisierung_Stat_LE,
	[Description("</STRUCT_PcbBearbeitungAbgebrochen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Pcb_Processing_Aborted_Request")]
	[DescriptionChinese("PCB中止处理_请求")]
	PcbBearbeitungAbgebrochen_Anfo_EL,
	[Description("</STRUCT_ProgrammAuswaehlen_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Select_Program_Request")]
	[DescriptionChinese("选择焊接程序_请求")]
	ProgrammAuswaehlen_Anfo_LE,
	[Description("</STRUCT_ProgrammAuswaehlen_Stat_EL>")]
	[Edc_MesFunctionEnglish("Select_Program_Response")]
	[DescriptionChinese("选择焊接程序_反馈")]
	ProgrammAuswaehlen_Stat_EL,
	[Description("</STRUCT_ErsasoftTriggern_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Ersasoft_Triggering_Request")]
	[DescriptionChinese("Ersasoft触发器_反馈")]
	ErsasoftTriggern_Anfo_LE,
	[Description("</STRUCT_LoetprogrammeUebertragen_Anfo_LE>")]
	[Edc_MesFunctionEnglish("Transferring_Soldering_Programs_Request")]
	[DescriptionChinese("转移焊接程序_请求")]
	LoetprogrammeUebertragen_Anfo_LE,
	[Description("</STRUCT_LoetprogrammeUebertragen_Stat_EL>")]
	[Edc_MesFunctionEnglish("Transferring_Soldering_Programs_Response")]
	[DescriptionChinese("转移焊接程序_反馈")]
	LoetprogrammeUebertragen_Stat_EL,
	[Description("</STRUCT_VerbindungAufbauen_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Build_Connection_Request")]
	[DescriptionChinese("建立连接_请求")]
	VerbindungAufbauen_Anfo_EL,
	[Description("</STRUCT_VerbindungAufbauen_Stat_LE>")]
	[Edc_MesFunctionEnglish("Build_Connection_Response")]
	[DescriptionChinese("建立连接_反馈")]
	VerbindungAufbauen_Stat_LE,
	[Description("</STRUCT_HeartbeatVonErsa_Anfo_EL>")]
	[Edc_MesFunctionEnglish("HeartBeat_by_Ersa_Request")]
	[DescriptionChinese("Ersa心跳包_请求")]
	HeartbeatVonErsa_Anfo_EL,
	[Description("</STRUCT_HeartbeatVonErsa_Stat_LE>")]
	[Edc_MesFunctionEnglish("HeartBeat_by_Ersa_Response")]
	[DescriptionChinese("Ersa心跳包_反馈")]
	HeartbeatVonErsa_Stat_LE,
	[Description("</STRUCT_VerbindungBeenden_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Stop_Connect_Request")]
	[DescriptionChinese("连接停止_请求")]
	VerbindungBeenden_Anfo_EL,
	[Description("</STRUCT_VerbindungBeenden_Stat_LE>")]
	[Edc_MesFunctionEnglish("Stop_Connect_Response")]
	[DescriptionChinese("连接停止_反馈")]
	VerbindungBeenden_Stat_LE,
	[Description("</STRUCT_BenutzerAnAbmelden_Anfo_EL>")]
	[Edc_MesFunctionEnglish("User_Sign_In/Out_Request")]
	[DescriptionChinese("用户登录_请求")]
	BenutzerAnAbmelden_Anfo_EL,
	[Description("</STRUCT_BenutzerAnAbmelden_Stat_LE>")]
	[Edc_MesFunctionEnglish("User_Sign_In/Out_Response")]
	[DescriptionChinese("用户登录_反馈")]
	BenutzerAnAbmelden_Stat_LE,
	[Description("</STRUCT_RuestWerkzeugMelden_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Ruest_Tool_Report_Request")]
	[DescriptionChinese("工具报告_请求")]
	RuestWerkzeugMelden_Anfo_EL,
	[Description("</STRUCT_RuestWerkzeugMelden_Stat_LE>")]
	[Edc_MesFunctionEnglish("Ruest_Tool_Report_Response")]
	[DescriptionChinese("工具报告_反馈")]
	RuestWerkzeugMelden_Stat_LE,
	[Description("</STRUCT_RuestMediumMelden_Anfo_EL>")]
	[Edc_MesFunctionEnglish("Ruest_Medium_Report_Request")]
	[DescriptionChinese("媒体报告_请求")]
	RuestMediumMelden_Anfo_EL,
	[Description("</STRUCT_RuestMediumMelden_Stat_LE>")]
	[Edc_MesFunctionEnglish("Ruest_Medium_Report_Response")]
	[DescriptionChinese("媒体报告_反馈")]
	RuestMediumMelden_Stat_LE
}
